name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 4.1.0
homepage: https://github.com/justkawal/excel
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  archive: ^4.0.2
  xml: ^6.5.0
  collection: ^1.15.0
  equatable: ^2.0.7

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
